# Generated by Django 4.0.5 on 2022-06-19 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=300)),
                ('adresse', models.CharField(max_length=200)),
                ('tel', models.CharField(max_length=20)),
                ('fixe', models.CharField(max_length=20)),
                ('facebook', models.CharField(max_length=300)),
                ('twitter', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.FloatField()),
                ('value_aoraire', models.TimeField()),
                ('description', models.TextField()),
                ('cible', models.CharField(max_length=100)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.association')),
            ],
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('montant', models.FloatField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Douateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_debut', models.DateTimeField()),
                ('date_fine', models.DateTimeField()),
                ('nbr_particip', models.IntegerField()),
                ('tarif', models.FloatField()),
                ('image', models.ImageField(upload_to='EvenementEmage')),
            ],
        ),
        migrations.CreateModel(
            name='Mumbre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('nationalite', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(upload_to='photos')),
                ('tel', models.CharField(max_length=20)),
                ('fixe', models.CharField(max_length=20)),
                ('date_naissance', models.DateTimeField()),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.association')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('heure_debut', models.TimeField()),
                ('heure_fine', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.association')),
                ('mumbre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.mumbre')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.FloatField()),
                ('nbr_etudient', models.IntegerField()),
                ('date_debut', models.DateTimeField()),
                ('date_fine', models.DateTimeField()),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.cours')),
            ],
        ),
        migrations.CreateModel(
            name='EvenementParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.evenement')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.participant')),
            ],
        ),
        migrations.CreateModel(
            name='DouateurAss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.association')),
                ('douateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.douateur')),
            ],
        ),
    ]
