# Generated by Django 4.0.5 on 2022-06-19 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='evenement',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='web.evenement'),
            preserve_default=False,
        ),
    ]
