# Generated by Django 4.0.5 on 2022-06-23 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_session_evenement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mumbre',
            old_name='nome',
            new_name='nom',
        ),
        migrations.AddField(
            model_name='evenement',
            name='heu',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='association',
            name='facebook',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='association',
            name='twitter',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
