# Generated by Django 4.0.5 on 2022-06-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_douateurass_montant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='douateurass',
            name='date',
            field=models.DateField(),
        ),
    ]
